version: '3'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8092
    volumes:
      - .:/app
    ports:
      - "8092:8092"
    depends_on:
      - db  # Ensure that the web service waits for the db service to be ready
    environment:
      - DATABASE_URL=postgres://sonar:sonar@db:5432/sonar
    networks:
      - sonarnet

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    networks:
      - sonarnet
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    networks:
      - sonarnet
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
