# Utilisez l'image officielle de Python comme base
FROM python:3.9

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le fichier des dépendances dans le répertoire de travail
COPY requirements.txt .

# Installez les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiez le contenu de votre projet dans le conteneur
COPY . .

# Exposez le port utilisé par Django
EXPOSE 8090

# Commande pour lancer l'application Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8090"]
