version: '3'

services:
  web:
    #image: hajer139/dashdor:latest  # Change this to main if needed
    command: python manage.py runserver 0.0.0.0:8092
    volumes:
      - .:/app
    ports:
      - "8092:8092"
